### ISSUE TITLE
[Feature Request] 'Update' button

### ISSUE THREAD

**Issue by boomam** [getwud/wud#210]
For those of us that dont want to automate updating, it would be good to retain watching ability, but have the ability to press an 'update' button to update.

**Comment by thedafa** [comment]
I would like automatic update for selected containers (a list of free-to-update items could be given to wud with variables/labels), but for other very important ones I would like to be more in control. So an manual update button would be an awesome idea.

**Comment by PiotrEsse** [comment]
+1

**Comment by ducadk** [comment]
+1

**Comment by Zatow** [comment]
I'm the same with @boomam, I want to monitor my containers for updates and deploy them with an "Update" button

**Comment by derekoharrow** [comment]
This would be awesome. I'm currently using Watchtower to auto-update some containers, and WUD to tell me when the rest need updating. Having this option to manually update certain containers would mean I could just use WUD.
(I guess I could also run two instances of WUD - one just to notify and one to auto-update, but that seems excessive).

**Comment by JvdMaat** [comment]
This has also been discussed as part of the update entity in HA. Issue is closed, but referencing it here to maintain easy-access history: https://github.com/fmartinou/whats-up-docker/issues/186#issuecomment-1344603845
There was some initial discussion on how to get this setup.

**Comment by kirk56k** [comment]
I would love to see this feature. I'll add my plus one to this as well.

**Comment by fmartinou** [comment]
I've started to work on a proof-of-concept few weeks ago...
It involves a big rework and because I don't have much time these days, it will last a bit before it's done.
But it will be ready sooner or later 😁 .

**Comment by loeffelpan** [comment]
What about Hass Integration? You create update-entities in hass. What does clicking "Update" in hass do today? And what should it do concerning this feature?

**Comment by fmartinou** [comment]
> You create update-entities in hass. What does clicking "Update" in hass do today? 

Currently you cannot click on the hass `update` button because it has been disabled.
You can only `skip` the available update

![image](https://github.com/fmartinou/whats-up-docker/assets/16061231/c5ce9f68-c65a-4fb1-8bfa-661ceb1d3b45)


> What about Hass Integration? And what should it do concerning this feature?

This github issue will provide `triggers` the capability to receive container update commands (`mqtt` topic, `http` request, `telegram` command, `ui` action...) and `wud` will update the container using the appropriate `watcher` (`docker`, `docker-compose`...)

Regarding Home-Assistant integration:
- All containers managed by WUD will be added as Home-assistant `devices`
- All container properties will be added as Home-Assistant 'entities`
- Every container will get an [`update entity`](https://www.home-assistant.io/integrations/update/) in Home-Assistant
- The `update entity` will provide info regarding the current / next version
- The `update entity` will allow to update the container when clicking the `Update button`

**Comment by JvdMaat** [comment]
I'm really looking forward to this!

Question, do you have an open issue for the "Read release announcement" link pointing to the old version (ie 3.1.2 in the Tydom screenshot you posted above), or will that get fixed with this issue as well? (I'd be happy to log an issue if needed for that)

**Comment by fmartinou** [comment]
> Question, do you have an open issue for the "Read release announcement" link pointing to the old version (ie 3.1.2 in the Tydom screenshot you posted above), or will that get fixed with this issue as well? (I'd be happy to log an issue if needed for that)

It should fix that one as well 🤞 .
(because `wud` containers will be treated as home-assistant `devices` instead of home-assistant `entities`)

**Comment by armond1978** [comment]
@fmartinou Thanks for considering this feature request. Is there any update or ETA?

**Comment by DanZirnhelt** [comment]
Bump.  Is this still a feature being worked on at all?

**Comment by filikun** [comment]
This looks really promising. I always wondered why there is no watchtower-ish application that can monitor containers for new versions and then just provide a simple notification and an update button. It's either a notification and do the manual update or automatic updates lol.

**Comment by Daemonias** [comment]
Bump

I agree with my foreposters

**Comment by armond-avanes** [comment]
@fmartinou Does version 7.2.0 (and PR: https://github.com/getwud/wud/pull/505) fix this issue?

**Comment by fmartinou** [comment]
Unfortunately, no, it.s not.
This pr only brings the ability to run a trigger with fake data to help validate that the trigger configuration is valid and works.

**Comment by Daemonias** [comment]
> Unfortunately, no, it.s not.
> This pr only brings the ability to run a trigger with fake data to help validate that the trigger configuration is valid and works.

Will that issue be tackled sometime soon?

**Comment by JvdMaat** [comment]
I just found out there's a 7.0 for WUD.. My WUD never alerted me to the new version. It still thought the 6.6.1 version was the latest.
So anyone using WUD (or watchtower I suppose, or any other), would not know about the change to getwud because it was looking at the old docker hub location, which did not publish the 7.0.0 info with the breaking change update info.

**Comment by fmartinou** [comment]
> So anyone using WUD (or watchtower I suppose, or any other), would not know about the change to getwud because it was looking at the old docker hub location, which did not publish the 7.0.0 info with the breaking change update info.

Hi, yes, that's right; `wud` location has changed.
It's exceptionally rare and it should not occur again.

**Comment by matheusvellone** [comment]
Just a heads up for anyone trying this feature for the first time.
When creating a new Docker trigger [as in the example](https://getwud.github.io/wud/#/configuration/triggers/docker/), I would recommend to also configure the trigger with `WUD_TRIGGER_DOCKER_EXAMPLE_AUTO=false` to avoid all images being updated automatically 🤣 😢 

I had ~20 containers outdated, and had a small surprise. At least they're all updated 😄

**Comment by SiriosDev** [comment]
Soooo, since is closed as completed, what needs to be done to make the update button appear?
