### ISSUE TITLE
WUD doesn't understand WUD's versioning

### ISSUE THREAD

**Issue by ajpanton** [getwud/wud#530]
What's the logic behind WUD's own version numbering on Docker Hub?

What seems to be the latest version has tags:
```
main
feature__501_multiple_custom_registries
latest
```
although I'm not sure... they were released on the same day, have identical sizes, but different digests.

The previous release two days earlier has tags:
```
7.2.0
dependabot_npm_and_yarn_app_multi-6bc014718a
feature__502_specific_triggers
```
again released on the same day, (almost) identical sizes, and different digests.

I'm using image 7.2.0 as per all recommendations here, but WUD freaks out and tries to recommend to me version 502 as obviously a bigger number than 7. What are these terrible version names that don't even increase consistently, and the lack of an actual version number for the latest version? I can't think of a rule that WUD itself doesn't break here.

**Comment by fmartinou** [comment]
Hi,

All feature / fix branches are pushed to the registries to allow people to validate them before merging them.
That's why you can see `feature__501_multiple_custom_registries` or `fix_blablabla` tags on the Hub.

The `main` tag matches with the latest build of the `main` branch.

The `latest` tag is pointing to the latest published release (currently `7.2.0`)

There was a pending issue regarding `latest` tag misaligned (#513); it should now work as expected 🤔 

> WUD freaks out and tries to recommend to me version 502 as obviously a bigger number than 7.

Add a regex to constraint `wud` to look for `semver` tags
```yaml
    wud:
        image: getwud/wud:7.2.0
        labels:
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
```
